load("@rules_python//python:defs.bzl", "py_library")

# Source libraries
py_library(
    name = "calculator",
    srcs = [
        "__init__.py",
        "calculator.py",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "string_utils",
    srcs = [
        "__init__.py",
        "string_utils.py",
    ],
    visibility = ["//visibility:public"],
)
